# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o bingo.o
LINKOBJ  = main.o bingo.o
LIBS     = -L"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/lib" -L"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/include" -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/include" -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Users/이정연/Documents/KakaoTalk/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) -std=c99
CFLAGS   = $(INCS) -std=c99
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

bingo.o: bingo.c
	$(CC) -c bingo.c -o bingo.o $(CFLAGS)
